// <auto-generated />
using System;
using CRS.Offer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRS.Offer.Infrastructure.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20250127191723_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("CRS.Offer.Core.Entities.Master", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Masters");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.MasterService", b =>
                {
                    b.Property<Guid>("MasterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.HasKey("MasterId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("MasterServices");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.Office", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WhatDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MasterId");

                    b.HasIndex("OfficeId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MasterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.Master", b =>
                {
                    b.HasOne("CRS.Offer.Core.Entities.Office", "Office")
                        .WithMany("Masters")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.MasterService", b =>
                {
                    b.HasOne("CRS.Offer.Core.Entities.Master", "Master")
                        .WithMany("MasterService")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRS.Offer.Core.Entities.Service", "Service")
                        .WithMany("MasterService")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.Schedule", b =>
                {
                    b.HasOne("CRS.Offer.Core.Entities.Master", "Master")
                        .WithMany("Schedules")
                        .HasForeignKey("MasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRS.Offer.Core.Entities.Office", "Office")
                        .WithMany("Schedules")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Master");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.Service", b =>
                {
                    b.HasOne("CRS.Offer.Core.Entities.Office", "Office")
                        .WithMany("Services")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.Master", b =>
                {
                    b.Navigation("MasterService");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.Office", b =>
                {
                    b.Navigation("Masters");

                    b.Navigation("Schedules");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("CRS.Offer.Core.Entities.Service", b =>
                {
                    b.Navigation("MasterService");
                });
#pragma warning restore 612, 618
        }
    }
}
